//! The published document.
//!
//! # What a generated document owes its reader
//!
//! Three things, and the header carries all three:
//!
//! 1. **That it is generated**, so nobody edits it and loses the edit.
//! 2. **What tree it describes**, so a number can be traced to the code that
//!    produced it. A results document without a commit is a rumour.
//! 3. **What it does not cover.** Every limit below is a real one that changes
//!    numbers in this document, and stating them is not modesty — a reader who
//!    treats a CPM number as a measurement of CPMA, or a number here as
//!    surviving `pmove_msec` sub-stepping, will draw a wrong conclusion from a
//!    correct measurement.

use std::fmt::Write as _;

use crate::dataset::{Block, Dataset, Section};

/// Where the document is written by default.
pub const DEFAULT_PATH: &str = "docs/movement-lab.md";

/// Where the pinned dataset the regression test reads is kept.
pub const PINNED_PATH: &str = "tools/straf3-lab/measurements.pinned.tsv";

/// The command that regenerates everything.
pub const COMMAND: &str = "cargo xtask lab";

/// What the document says about the tree it was measured from.
///
/// Passed in rather than discovered, and that is the whole design of this type.
/// A tool that shelled out to `git rev-parse` itself would produce a different
/// document on every commit — including commits that changed nothing it
/// measures — so `--check` could never be green and the fixture could never be
/// stable. Provenance is therefore *outside* the deterministic part: the
/// measurements do not depend on it, and the regression test does not read it.
#[derive(Debug, Clone)]
pub struct Provenance {
    /// The commit the measurements were taken from, or a note saying it was not
    /// recorded.
    pub tree: String,
    /// Whether the working tree had uncommitted changes at that commit.
    pub dirty: bool,
}

impl Provenance {
    /// What is printed when nobody told the lab what tree it is measuring.
    ///
    /// Deliberately loud. A document that quietly said nothing about its
    /// provenance would look complete.
    #[must_use]
    pub fn unrecorded() -> Self {
        Self {
            tree: "UNRECORDED — run via `cargo xtask lab`, which fills this in".to_string(),
            dirty: false,
        }
    }

    /// A recorded commit.
    #[must_use]
    pub fn at(tree: impl Into<String>, dirty: bool) -> Self {
        Self {
            tree: tree.into(),
            dirty,
        }
    }

    fn render(&self) -> String {
        if self.dirty {
            format!("`{}` **plus uncommitted changes**", self.tree)
        } else {
            format!("`{}`", self.tree)
        }
    }
}

/// Render the whole document.
#[must_use]
pub fn render(sections: &[Section], data: &Dataset, provenance: &Provenance, mirrored: bool) -> String {
    let mut out = String::new();

    let _ = writeln!(
        out,
        "<!-- GENERATED BY `{COMMAND}`. DO NOT EDIT: your changes will be \
         overwritten the next time it runs. -->"
    );
    let _ = writeln!(out, "\n# The movement lab");
    let _ = writeln!(
        out,
        "\nMeasured from {} by `{COMMAND}`, which runs `tools/straf3-lab`.",
        provenance.render()
    );
    let _ = writeln!(
        out,
        "\nEvery number below was produced by running the simulation. Nothing here \
         is a constant restated: where a value is also a constant in \
         `PhysicsProfile`, the report says so and prints both, because a constant \
         that is stored and never read is indistinguishable from one that is used \
         until something measures it."
    );

    // ── conditions ────────────────────────────────────────────────────────
    let _ = writeln!(out, "\n## Conditions\n");
    let _ = writeln!(
        out,
        "| | |\n|---|---|\n\
         | Command rate | 125 Hz — 8 ms commands, spec D2's default. Not swept; see *Limits*. |\n\
         | Profiles | {} |\n\
         | Worlds | Brushes compiled by `straf3-collision`, traced by the tracer the game uses. {} |\n\
         | Measurements | {} named values, in the machine-readable section at the end. |\n\
         | Determinism | No clock, no randomness, no parallelism, no libm on any path that feeds a number. Same invocation, same bytes. |",
        crate::measure::profiles()
            .iter()
            .map(|(n, _)| format!("`{n}`"))
            .collect::<Vec<_>>()
            .join(", "),
        if mirrored {
            "**These are the lab's mirror of `straf3_collision::testbed`, not the module itself** \
             — see *Limits*."
        } else {
            "The shared `straf3_collision::testbed` fixtures, the same ones the sim tests pin \
             behaviour against."
        },
        data.len(),
    );

    // ── limits, before the numbers rather than after ──────────────────────
    let _ = writeln!(out, "\n## Limits\n");
    let _ = writeln!(
        out,
        "These are stated first because each one changes how a number below \
         should be read.\n"
    );
    let _ = writeln!(
        out,
        "1. **`pmove_msec` sub-stepping is not implemented** (`crates/straf3-sim/src/step.rs`, \
         `TODO(wave3)`). Quake 3 splits a long command into sub-steps so a large \
         duration cannot tunnel through geometry or skip a jump window. This tree \
         integrates each command once. **Every number in this document is valid \
         for the current single-step integration only.** Section 4 is the one \
         most exposed: overbounce's precondition is a command that *ends* with \
         the player's feet inside the ground probe, which is a per-command \
         artefact, and sub-stepping moves the command boundary. Both this seat \
         and the sim seat expect those counts to change; **neither has measured \
         it**, because the sub-stepping does not exist yet. That is an open \
         question, not a settled one."
    );
    let _ = writeln!(
        out,
        "2. **CPM's constants are community reconstructions, not id source** \
         (`crates/straf3-sim/src/profile.rs`). `air_control` 150, \
         `air_stop_accelerate` 2.5, `strafe_accelerate` 70, \
         `strafe_wish_speed_cap` 30, the 400 ms double-jump window and its 100 ups \
         boost are all `TODO(wave2)`. **A `cpm` number in this document is a \
         measurement of this tree, not of CPMA.** The `vq3` numbers are different \
         in kind: those constants are verified against id's GPL release."
    );
    let _ = writeln!(
        out,
        "3. **One command rate.** Everything is at 125 Hz. The rate is part of the \
         physics, not of the frame loop, so 76 Hz and 250 Hz are different \
         simulations with different jump heights and different usable windows. \
         Sweeping the rate is a report this one does not contain."
    );
    if mirrored {
        let _ = writeln!(
            out,
            "4. **The worlds are the lab's mirror of the shared fixtures.** \
             `straf3_collision::testbed` is the single owner of the ramp, step, \
             ledge and corner geometry, so that a sim test pinning a behaviour \
             and a lab measurement quantifying it are talking about the same \
             world. It was not yet in this workspace when these numbers were \
             taken, so `tools/straf3-lab/src/geometry.rs` reproduces it from the \
             published API and coordinate table — same constructors, same \
             constants, same coordinates, same `compile_hull` path. **The \
             measurements in sections 3 and 5 must be re-taken against the real \
             module and compared before they are trusted as the shared \
             number.**"
        );
    }
    let _ = writeln!(
        out,
        "{}. **No human input.** Every technique here is held exactly. A player \
         holds it imperfectly, so these are ceilings, not expectations.",
        if mirrored { 5 } else { 4 }
    );
    let _ = writeln!(
        out,
        "{}. **Route diversity is not measured here.** Whether `coil` offers \
         enough distinct routes to judge a mechanic against is a real open \
         question and is deliberately not answered: the only perturbation \
         harness that exists varies an *absolute*-view-angle command stream, so \
         a perturbed run is not a delayed run but a different one aimed at \
         geometry the angles were never chosen for. A measurement worth \
         publishing would perturb something a player controls — entry speed, \
         turn rate, launch timing — against angles expressed relative to the \
         current heading. It stays open rather than being answered badly.",
        if mirrored { 6 } else { 5 }
    );
    let _ = writeln!(
        out,
        "{}. **`overclip` is not the dial these behaviours turn on**, despite \
         what the comment on `PhysicsProfile::overclip` implies. The sim seat \
         measured setting it to 1.0 and found it changes these numbers by a \
         fraction of a percent everywhere except a player landing exactly \
         perpendicular onto flat ground. This report deliberately carries no \
         `overclip` sensitivity column: it would be a column of zeros presented \
         as an analysis. What the behaviours actually turn on is \
         `PM_WalkMove`'s length-preserving rescale and the 0.25-unit ground \
         probe.",
        if mirrored { 7 } else { 6 }
    );

    // ── the measurements ──────────────────────────────────────────────────
    for section in sections {
        let _ = writeln!(out, "\n## {}\n", section.title);
        for block in &section.blocks {
            match block {
                Block::Prose(p) => {
                    let _ = writeln!(out, "{p}\n");
                }
                Block::Table(t) => {
                    let _ = writeln!(out, "{}", t.render());
                }
            }
        }
    }

    // ── the machine-readable section ──────────────────────────────────────
    let _ = writeln!(out, "\n## Machine-readable results\n");
    let _ = writeln!(
        out,
        "Every measurement above, as `key<TAB>value<TAB>unit`, sorted by key. \
         This is the same text as `{PINNED_PATH}`, which `cargo test -p \
         straf3-lab` compares against and which names the measurements that \
         moved when it fails.\n"
    );
    let _ = writeln!(out, "```tsv\n{}```", data.to_tsv());

    out
}

/// The pinned dataset file, with the header that explains what it is.
#[must_use]
pub fn render_pinned(data: &Dataset) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# GENERATED BY `{COMMAND}`. Do not hand-edit — regenerate it.\n\
         #\n\
         # These are the movement numbers this tree produces. `cargo test -p \
         straf3-lab`\n\
         # recomputes them and fails on any difference, naming which \
         measurement moved.\n\
         # A change here is a change to how the game moves: it belongs in the \
         same commit\n\
         # as the movement change that caused it, with the reason in the \
         message.\n\
         #\n\
         # Format: key<TAB>value<TAB>unit, sorted by key."
    );
    out.push_str(&data.to_tsv());
    out
}
