//! `wishbone` — the crate-internal course the r9 demonstration is measured on.
//!
//! # What this map is for, and what it is not
//!
//! r9 asks for a search that can prefer an action scoring worse at its horizon
//! because it is better at the goal, *demonstrated*. A demonstration needs
//! geometry where a greedy search provably takes the wrong branch, and neither
//! shipped map has any: `coil` is a corridor a one-step hill climber already
//! completes, and `training-crouch-slide` is a corridor too — hard for a
//! different reason, its lintel demanding a CROUCH, which is a fact about the
//! alphabet rather than about lookahead.
//!
//! So this crate cuts its own. It is **a fixture, not a first-party map**: it
//! lives under `tools/straf3-agent/fixtures/`, not `assets/maps/`, it is
//! generated by [`wishbone`] rather than authored, and main's ruling is that a
//! crate-internal fixture may discharge **r9** and may not discharge **r11**.
//! Route choice on geometry the agent's author never saw is `cleave`'s job.
//!
//! # The shape, and why each piece is the shape it is
//!
//! Two forks in series, mirrored. Each is the failure `probes/course-lab`
//! measured on `cleave` reduced to its essentials: **the branch that points
//! straight at the next goal is the one that ends in a hole.**
//!
//! - The checkpoint after each fork sits **off to one side**, so the lane on that
//!   side is closer to it at every moment of the approach. That is what makes
//!   the trap the horizon-argmax rather than merely available.
//! - That lane's floor is **absent**: it is a 160-unit pit, walled on all four
//!   sides and sealed flush with the main floor at its north end. Entering it
//!   *reduces* the distance to the goal — the hull gains more in `y` than it
//!   loses in `z` — and cannot be left. A drop rather than a ramp on purpose: a
//!   ramp shallow enough to be attractive is shallow enough to walk back up, and
//!   b7's S6 voids a demonstration whose trap is recoverable.
//! - The other lane is clear, and reaching the checkpoint from it costs a
//!   lateral move **away** from the goal first. That is the alternative that is
//!   worse at the horizon and better at the goal.
//! - The divider between them is 32 units wide and offset **80 units onto the
//!   clear side**, so the wider lane — the one a player running straight ends up
//!   in, having done nothing — is the punishing one.
//!
//! The second fork mirrors the first: its checkpoint and its pit are on the
//! opposite side, and the run arrives at it already displaced toward the trap by
//! the checkpoint it has just crossed. This is b7's **S3**, and it is the clause
//! that matters most for whether the demonstration means anything: a search with
//! a hidden "prefer west" bias passes one fork by luck and cannot pass two whose
//! correct branches point opposite ways.
//!
//! Between the start line and the first divider lie **1024 units of straight,
//! identical corridor**. Both branches of every claim made about this map share
//! it, so a difference between two runs is a difference in what they did at a
//! fork rather than in how they left the spawn.
//!
//! # This file's constants are map constants, and that is not an r27 violation
//!
//! r27 forbids a map-specific constant *in the agent's source* — in the thing
//! that decides where to go. Every number below describes the map this module
//! writes, the way every number in a `.map` file describes the map it is. The
//! agent reads this course through exactly the path it reads `coil` through:
//! `straf3_map::compile`, then [`crate::course::CoursePlan::derive`]. Nothing in
//! [`crate::course`] or [`crate::search`] refers to this module, and the
//! dependency runs one way only.
//!
//! # Verdict conditions this fixture declares against itself
//!
//! Written before the search was run against it, and kept whatever the numbers
//! say. **This fixture is void as an r9 demonstration if:**
//!
//! 1. the greedy control does *not* enter a pit lane — then the trap is not the
//!    horizon-argmax and the fixture fails b7's G3, whatever the full search
//!    does;
//! 2. the pit turns out to be escapable — then the trap is recoverable, greedy
//!    recovers, and b7's S6 and G4 both fail;
//! 3. the full search completes it only at exactly one frontier width and fails
//!    at every other — then b7's S1 says two numbers were fitted to each other
//!    rather than a property demonstrated.
//!
//! None of the three is asserted here to be false. They are checked in
//! `results/`, by running the thing.

use crate::brush::{box_brush, brush_entity, point_entity, timed_trigger_with};

// ---------------------------------------------------------------------------
// The dimensions. All of them describe this map and none of them is read by the
// agent — see the module docs.

/// Half-width of the running corridor.
const HALF_WIDTH: i32 = 320;
/// Top of the floor the run happens on.
const FLOOR_TOP: i32 = 0;
/// Bottom of the floor slabs.
const FLOOR_BOTTOM: i32 = -64;
/// Ceiling height.
const CEILING: i32 = 352;
/// Surface a player who fell into a pit lands on: 160 units down, which is more
/// than a standing jump's apex plus a step, so the fall is one-way.
const PIT_TOP: i32 = -160;
/// Bottom of the pit's own floor slab.
const PIT_BOTTOM: i32 = -224;
/// Thickness of the perimeter shell.
const SHELL: i32 = 64;
/// Half-thickness of a divider: the wall between two lanes is 32 units wide.
const DIVIDER_HALF: i32 = 16;
/// How far the divider sits from the centre line, toward the clear lane, so the
/// lane a player reaches by running straight is the punishing one.
const DIVIDER_OFFSET: i32 = 80;

/// Where the player stands at `t = 0`.
const SPAWN_Y: i32 = -192;
/// The start line.
const START_Y: (i32, i32) = (0, 64);
/// The blind run: 1024 units of corridor identical for every claim.
const BLIND_RUN_END: i32 = 1088;
/// First fork, from the divider's south end to its north end.
const FORK1: (i32, i32) = (1088, 1856);
/// The checkpoint the first fork's trap points at.
const CP0_Y: (i32, i32) = (2112, 2176);
/// The checkpoint that pulls the run back across the corridor before fork two.
const CP1_Y: (i32, i32) = (2368, 2432);
/// Second fork, mirrored.
const FORK2: (i32, i32) = (2560, 3328);
/// The finish line, which the second fork's trap points at.
const FINISH_Y: (i32, i32) = (3584, 3648);
/// North end of the world.
const WORLD_END: i32 = 3776;
/// How far a side volume reaches in from its wall.
const SIDE_INSET: i32 = 256;
/// Trigger volumes span this in `z`, matching the shipped maps' habit of a tall
/// volume a player cannot pass without crossing.
const TRIGGER_Z: (i32, i32) = (-32, CEILING);

/// Which side of the corridor something is on.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Side {
    /// Negative `x`.
    West,
    /// Positive `x`.
    East,
}

impl Side {
    /// The opposite side.
    #[must_use]
    pub fn other(self) -> Self {
        match self {
            Self::West => Self::East,
            Self::East => Self::West,
        }
    }

    /// The sign that turns a westward measurement into one on this side.
    const fn sign(self) -> i32 {
        match self {
            Self::West => -1,
            Self::East => 1,
        }
    }

    /// The name that appears in the map's own comments and in a report.
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Self::West => "west",
            Self::East => "east",
        }
    }

    /// The `x` span of a volume inset from this side's wall.
    const fn inset_span(self) -> (i32, i32) {
        match self {
            Self::West => (-HALF_WIDTH, -HALF_WIDTH + SIDE_INSET),
            Self::East => (HALF_WIDTH - SIDE_INSET, HALF_WIDTH),
        }
    }
}

/// One fork: where its divider is, which lane is the pit, and where the goal it
/// points at sits.
#[derive(Debug, Clone, Copy)]
pub struct Fork {
    /// South and north ends of the divider.
    pub y: (i32, i32),
    /// The lane whose floor is missing.
    pub trap: Side,
}

impl Fork {
    /// The divider's `x` span. Offset toward the clear lane, so the trap lane is
    /// the wider one and a player who steers at nothing ends up in it.
    #[must_use]
    pub fn divider_x(self) -> (i32, i32) {
        let centre = DIVIDER_OFFSET * self.trap.other().sign();
        (centre - DIVIDER_HALF, centre + DIVIDER_HALF)
    }

    /// The trap lane's `x` span: from the divider to the wall on the trap side.
    #[must_use]
    pub fn trap_x(self) -> (i32, i32) {
        let (lo, hi) = self.divider_x();
        match self.trap {
            Side::West => (-HALF_WIDTH, lo),
            Side::East => (hi, HALF_WIDTH),
        }
    }

    /// The clear lane's `x` span.
    #[must_use]
    pub fn clear_x(self) -> (i32, i32) {
        let (lo, hi) = self.divider_x();
        match self.trap {
            Side::West => (hi, HALF_WIDTH),
            Side::East => (-HALF_WIDTH, lo),
        }
    }
}

/// The two forks this map poses, in the order a run meets them.
///
/// Mirrored on purpose, and this is the whole of b7's S3: fork one's clear lane
/// is east, fork two's is west. A search that prefers one direction gets exactly
/// one of them right.
#[must_use]
pub fn forks() -> [Fork; 2] {
    [
        Fork {
            y: FORK1,
            trap: Side::West,
        },
        Fork {
            y: FORK2,
            trap: Side::East,
        },
    ]
}

/// The side each declared goal sits on, in course order, for a report to check
/// the mirroring against rather than take on trust.
#[must_use]
pub fn goal_sides() -> [(&'static str, Option<Side>); 4] {
    [
        ("start", None),
        ("cp0", Some(forks()[0].trap)),
        ("cp1", Some(forks()[1].trap)),
        ("finish", Some(forks()[1].trap)),
    ]
}

// ---------------------------------------------------------------------------

fn floor(x: (i32, i32), y: (i32, i32)) -> String {
    box_brush(
        [x.0, y.0, FLOOR_BOTTOM],
        [x.1, y.1, FLOOR_TOP],
        "straf3/floor",
    )
}

fn wall(x: (i32, i32), y: (i32, i32), z: (i32, i32)) -> String {
    box_brush([x.0, y.0, z.0], [x.1, y.1, z.1], "straf3/wall")
}

/// The brushes of one fork: the divider, the pit's floor, and the four seals
/// that make the pit a box a player cannot leave.
fn fork_brushes(f: Fork) -> Vec<String> {
    let (y0, y1) = f.y;
    let (dx0, dx1) = f.divider_x();
    let (tx0, tx1) = f.trap_x();
    let mut out = Vec::new();

    // The divider, reaching from below the pit floor to the ceiling so it seals
    // the trap lane from the clear one at every height.
    out.push(wall((dx0, dx1), (y0, y1), (PIT_BOTTOM, CEILING)));

    // The clear lane keeps its floor for the fork's whole length.
    let clear = f.clear_x();
    out.push(floor(clear, (y0, y1)));

    // The trap lane has none: 160 units down to a floor of its own.
    out.push(box_brush(
        [tx0, y0, PIT_BOTTOM],
        [tx1, y1, PIT_TOP],
        "straf3/floor",
    ));

    // The south seal, under the corridor the run arrives along, so a player at
    // the bottom cannot walk back beneath the floor they fell from.
    out.push(wall((tx0, tx1), (y0 - 32, y0), (PIT_BOTTOM, FLOOR_BOTTOM)));

    // The north seal. Its top is flush with the main floor, so a run at `z = 0`
    // walks over it and one at `z = -160` faces a wall it cannot climb. This is
    // the piece that makes the trap costly rather than a detour.
    out.push(wall(
        (tx0, tx1),
        (y1, y1 + 32),
        (PIT_BOTTOM, FLOOR_TOP),
    ));

    out
}

/// Generate `wishbone.map`.
///
/// Deterministic: the same text every time, which is what lets a test compare
/// the committed file against this function and fail if either drifts.
#[must_use]
pub fn wishbone() -> String {
    let full = (-HALF_WIDTH, HALF_WIDTH);
    let [f1, f2] = forks();

    let mut world = String::new();

    // ---- the floor, in the segments the forks leave of it -------------------
    world.push_str(&floor(full, (SPAWN_Y - SHELL, BLIND_RUN_END)));
    for b in fork_brushes(f1) {
        world.push_str(&b);
    }
    world.push_str(&floor(full, (f1.y.1, f2.y.0)));
    for b in fork_brushes(f2) {
        world.push_str(&b);
    }
    world.push_str(&floor(full, (f2.y.1, WORLD_END)));

    // ---- the shell ----------------------------------------------------------
    let span = (SPAWN_Y - SHELL, WORLD_END);
    world.push_str(&wall(
        (-HALF_WIDTH - SHELL, -HALF_WIDTH),
        span,
        (PIT_BOTTOM, CEILING),
    ));
    world.push_str(&wall(
        (HALF_WIDTH, HALF_WIDTH + SHELL),
        span,
        (PIT_BOTTOM, CEILING),
    ));
    world.push_str(&wall(
        (-HALF_WIDTH - SHELL, HALF_WIDTH + SHELL),
        (SPAWN_Y - SHELL - SHELL, SPAWN_Y - SHELL),
        (PIT_BOTTOM, CEILING),
    ));
    world.push_str(&wall(
        (-HALF_WIDTH - SHELL, HALF_WIDTH + SHELL),
        (WORLD_END, WORLD_END + SHELL),
        (PIT_BOTTOM, CEILING),
    ));
    world.push_str(&wall(
        (-HALF_WIDTH - SHELL, HALF_WIDTH + SHELL),
        (SPAWN_Y - SHELL - SHELL, WORLD_END + SHELL),
        (CEILING, CEILING + SHELL),
    ));

    let mut map = brush_entity(
        "worldspawn",
        &[
            ("message", "wishbone"),
            (
                "_comment",
                "generated by straf3_agent::fixture::wishbone — do not hand-edit",
            ),
        ],
        &[world],
    );

    map.push_str(&point_entity(
        "info_player_start",
        &[("origin", &format!("0 {SPAWN_Y} 32")), ("angle", "90")],
    ));

    // ---- the timing volumes -------------------------------------------------
    // The start spans the corridor; every later one sits off to one side, which
    // is what points the greedy search at the lane with no floor in it.
    map.push_str(&timed_trigger_with(
        "target_startTimer",
        "t_start",
        &[],
        &[trigger_box(full, START_Y)],
    ));
    map.push_str(&timed_trigger_with(
        "target_checkpoint",
        "t_cp0",
        &[("count", "1")],
        &[trigger_box(f1.trap.inset_span(), CP0_Y)],
    ));
    map.push_str(&timed_trigger_with(
        "target_checkpoint",
        "t_cp1",
        &[("count", "2")],
        &[trigger_box(f2.trap.inset_span(), CP1_Y)],
    ));
    map.push_str(&timed_trigger_with(
        "target_stopTimer",
        "t_finish",
        &[],
        &[trigger_box(f2.trap.inset_span(), FINISH_Y)],
    ));
    map
}

fn trigger_box(x: (i32, i32), y: (i32, i32)) -> String {
    box_brush(
        [x.0, y.0, TRIGGER_Z.0],
        [x.1, y.1, TRIGGER_Z.1],
        "straf3/trigger",
    )
}

/// Where the committed copy lives, relative to this crate's manifest.
pub const PATH: &str = "fixtures/wishbone.map";

#[cfg(test)]
mod tests;
