//! A sin/cos that cannot disagree across platforms, to test whether the
//! Q3-style "ship our own trig" fix actually closes the gap.
//!
//! The divergence this probe found is in `libm` itself: `sinf`/`cosf` are not
//! IEEE-754-specified, so glibc's and the Rust `libm` crate's (which is what
//! `wasm32-unknown-unknown` links) are free to round the last bit differently.
//! Everything here uses only `+ - * /` and comparisons on `f32`/`f64`, all of
//! which *are* IEEE-specified and are emitted as single wasm instructions with
//! no contraction, so the result is bit-identical by construction rather than
//! by luck.
//!
//! Shape: Cody–Waite range reduction to |r| ≤ π/4 in `f64`, then the Taylor
//! polynomials Quake's own approximations are cousins of, rounded once to
//! `f32` at the end. A 4096-entry lookup table generated by this function
//! would be equally deterministic — the table is an optimisation, the
//! determinism comes from not calling `libm`.

/// π/2 split in two so the reduction subtracts exactly-representable pieces:
/// `PIO2_HI` is the `f64` nearest π/2, `PIO2_LO` the residual it left behind.
const PIO2_HI: f64 = std::f64::consts::FRAC_PI_2;
const PIO2_LO: f64 = 6.123_233_995_736_766e-17;
const TWO_OVER_PI: f64 = std::f64::consts::FRAC_2_PI;

fn poly_sin(r: f64) -> f64 {
    let r2 = r * r;
    // r - r³/6 + r⁵/120 - r⁷/5040 + r⁹/362880
    r * (1.0
        + r2 * (-1.0 / 6.0 + r2 * (1.0 / 120.0 + r2 * (-1.0 / 5040.0 + r2 * (1.0 / 362_880.0)))))
}

fn poly_cos(r: f64) -> f64 {
    let r2 = r * r;
    // 1 - r²/2 + r⁴/24 - r⁶/720 + r⁸/40320
    1.0 + r2 * (-0.5 + r2 * (1.0 / 24.0 + r2 * (-1.0 / 720.0 + r2 * (1.0 / 40_320.0))))
}

/// Reduce `x` to (quadrant, remainder) with only IEEE arithmetic.
fn reduce(x: f64) -> (i64, f64) {
    // round-half-away-from-zero without calling round(): add ±0.5 and truncate.
    let scaled = x * TWO_OVER_PI;
    let q = (scaled + if scaled >= 0.0 { 0.5 } else { -0.5 }) as i64;
    let qf = q as f64;
    let r = (x - qf * PIO2_HI) - qf * PIO2_LO;
    (q, r)
}

/// Bit-identical `sin` for arguments in radians.
#[must_use]
pub fn det_sin(x: f32) -> f32 {
    let (q, r) = reduce(f64::from(x));
    let v = match q.rem_euclid(4) {
        0 => poly_sin(r),
        1 => poly_cos(r),
        2 => -poly_sin(r),
        _ => -poly_cos(r),
    };
    v as f32
}

/// Bit-identical `sin_cos`, shaped like `f32::sin_cos` so the patched copy of
/// the sim (see `build.rs`) is a three-line substitution.
#[must_use]
pub fn det_sin_cos(x: f32) -> (f32, f32) {
    let (q, r) = reduce(f64::from(x));
    let (sp, cp) = (poly_sin(r), poly_cos(r));
    let (s, c) = match q.rem_euclid(4) {
        0 => (sp, cp),
        1 => (cp, -sp),
        2 => (-sp, -cp),
        _ => (-cp, sp),
    };
    (s as f32, c as f32)
}

/// Bit-identical `cos` for arguments in radians.
#[must_use]
pub fn det_cos(x: f32) -> f32 {
    let (q, r) = reduce(f64::from(x));
    let v = match q.rem_euclid(4) {
        0 => poly_cos(r),
        1 => -poly_sin(r),
        2 => -poly_cos(r),
        _ => poly_sin(r),
    };
    v as f32
}
